frontend/src/App.tsx
frontend/src/components/Login/PetAdd.tsx
frontend/src/components/common/Header/index.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/pages/Login.tsx
frontend/tsconfig.app.json

- Login 기본 UI 및 component 생성
- Login 페이지 생성
- Login 페이지 기본 components 구현

[feat(fe)] Login 기본 UI 및 component 생성

---

frontend/src/styles/typo.tsx

[chore] typo 설정 수정

---

frontend/src/components/common/Typo/index.tsx
frontend/src/styles/theme.ts
frontend/src/styles/typo.tsx

- Text 컴포넌트 props 수정
- props에 웹 모바일 나누는거 필요없어서 통일

[style] Text 컴포넌트 props 수정

---

backend/src/entity/food.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts

- food, snack, supplement 엔티티 작성
- 기존 product 엔티티를 food, snack, supplement로 세분화

[feat] food, snack, suppplement-entity

---

frontend/src/components/common/Flex/index.tsx
frontend/src/components/common/Typo/index.tsx
frontend/src/styles/theme.ts
frontend/src/styles/typo.tsx

- [feat] Flex 컴포넌트 gap 수정
- [feat] Flex 컴포넌트 gap 수정

[feat] Flex 컴포넌트 gap 수정

---

backend/src/entity/allergy.entity.ts
backend/src/entity/base.entity.ts
backend/src/entity/cart.entity.ts
backend/src/entity/cart.product.entity.ts
backend/src/entity/food.entity.ts
backend/src/entity/health.entity.ts
backend/src/entity/order.entity.ts
backend/src/entity/orderItem.entity.ts
backend/src/entity/pet.entity.ts
backend/src/entity/product.entity.ts
backend/src/entity/productReview.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts
backend/src/entity/user.entity.ts

- entity type 수정
- entity 이름 수정

[fix] entity type 수정

---

README.md
frontend/src/App.tsx
frontend/src/assets/images/svgs/CloseIcon/WhiteCloseIcon.tsx
frontend/src/assets/images/svgs/CloseIcon/index.tsx
frontend/src/components/common/Flex/index.tsx
frontend/src/components/common/Footer/index.tsx
frontend/src/components/common/Header/index.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/components/common/Modal/Modal.stories.tsx
frontend/src/components/common/Modal/Modal.tsx
frontend/src/components/common/Modal/index.tsx
frontend/src/components/common/Modal/useModal.tsx
frontend/src/components/common/Navbar/NavItem.tsx
frontend/src/components/common/Navbar/index.tsx
frontend/src/components/common/Typo/Typo.stories.tsx
frontend/src/pages/Home.tsx
frontend/tsconfig.json
frontend/vite.config.ts

- LUP-46 공통 컴포넌트 구현
- modal 공통 컴포넌트 구현

[feat] modal 공통 컴포넌트 구현

---

backend/.gitignore
backend/src/app.module.ts
backend/src/entity/pet.entity.ts
backend/src/product/dto/food.dto.ts
backend/src/product/dto/snack.dto.ts
backend/src/product/dto/supplement.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts

초기 데이터 db에 저장
- 초기 product 데이터를 db에 저장했어요.
- product dto를 추가했어요.
- product 종류 dto인 snack,food,supplement을 추가했어요.

[feat] 초기 데이터 추가, entity 수정, product DTO 추가

---

frontend/src/components/common/Tag/Tag.stories.tsx
frontend/src/components/common/Tag/index.tsx
frontend/src/components/common/Typo/index.tsx
frontend/src/pages/Store/index.tsx
frontend/src/styles/tag.ts
frontend/src/styles/theme.ts
frontend/src/styles/typo.tsx
frontend/tsconfig.json

- Store UI 수정
- LUP-65
- Tag Component 생성

[feat] Tag Component 생성

---

frontend/src/components/common/Button/Button.stories.tsx
frontend/src/components/common/Button/Button.tsx
frontend/src/components/common/Button/index.tsx

- LUP-46
- 기본 컴포넌트 구현
- Button 기본 컴포넌트 생성 및 구현

[feat] Button 기본 컴포넌트 생성 및 구현

---

frontend/src/components/common/Button/Button.stories.tsx
frontend/src/components/common/Button/Button.tsx
frontend/src/components/common/Button/index.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/components/common/Navbar/NavItem.tsx
frontend/src/components/common/Navbar/Navbar.stories.tsx
frontend/src/components/common/Navbar/index.tsx

- LUP-46
- 기본 컴포넌트 수정
- navbar 컴포넌트 수정

[feat] navbar 컴포넌트 수정

---

backend/src/entity/allergy.entity.ts
backend/src/entity/cart.entity.ts
backend/src/entity/cart.product.entity.ts
backend/src/entity/food.entity.ts
backend/src/entity/order.entity.ts
backend/src/entity/orderItem.entity.ts
backend/src/entity/pet.entity.ts
backend/src/entity/product.entity.ts
backend/src/entity/productReview.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts
backend/src/entity/user.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts

- product list 및 detail product api 추가했어요!
- entity 중첩 명 수정과 import 에러도 해결했어요!

[feat] product list 및 detail product api 추가(LUP-63)

---

frontend/src/App.tsx
frontend/src/assets/types/ReviewType.ts
frontend/src/components/cart/Checkbox/index.tsx
frontend/src/components/store/detail/ProductReviewItem.tsx
frontend/src/components/store/detail/ReviewText.tsx
frontend/src/mocks/data/cart.json
frontend/src/pages/Cart/index.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Store/Detail.tsx

- 장바구니 페이지 레이아웃 구현
- 장바구니 페이지 레이아웃 구현
- 리뷰 타입 수정

[feat] 장바구니 페이지 레이아웃 구현

---

frontend/src/components/common/Navbar/Navbar.stories.tsx
frontend/src/components/store/Product/ProductHorizontal.stories.tsx
frontend/src/pages/Home.tsx

- 빌드 오타 및 에러 수정
- LUP-73
- productHorizontal storybook args 수정
- home 오타 제거
- navbar 타입 오류 수정

[fix] 빌드 오타 및 에러 수정

---

backend/src/entity/food.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.module.ts
backend/src/product/product.service.ts
backend/src/types/category.ts

- product list 및 detail product api 추가
- product 관련 entity가 수정되었습니다.

[feat] product list 및 detail product api 추가

---

backend/src/entity/allergy.entity.ts
backend/src/entity/base.entity.ts
backend/src/entity/health.entity.ts
backend/src/entity/pet.entity.ts

- issue
base entity를 수정했어요. base entity의 id가 사라짐에 따라서 각 테이블에 primary key 설정을 해줬어요!

[refact] base entity 수정

---

frontend/src/assets/types/CartType.tsx
frontend/src/components/cart/CartCost/index.tsx
frontend/src/components/cart/CartItem/index.tsx
frontend/src/components/cart/Checkbox/index.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/components/common/Navbar/index.tsx
frontend/src/components/store/detail/DetailButton.tsx
frontend/src/mocks/data/cart.json
frontend/src/pages/Cart/index.tsx
frontend/src/pages/Store/Detail.tsx
frontend/src/pages/Store/index.tsx

- cart 페이지 컴포넌트 분할
- Layout과 Navbar css 수정
- cart 페이지 컴포넌트 분할, Layout과 Navbar css 수정

[chore] cart 페이지 컴포넌트 분할, Layout과 Navbar css 수정

---

backend/src/auth/auth.controller.ts
backend/src/configs/setupSwagger.ts
backend/src/configs/typeorm.config.ts
backend/src/entity/allergy.entity.ts
backend/src/entity/user.entity.ts
backend/src/mypage/dto/getUserResponse.dto.ts
backend/src/mypage/dto/updatePet.dto.ts
backend/src/mypage/mypage.controller.ts
backend/src/mypage/mypage.module.ts
backend/src/mypage/mypage.service.ts

- 유저 펫 정보 조회
- 서버 API 요청 성공
- 펫 정보 조회

[feat(be)] API요청, 유저의 펫 정보 조회

---

backend/src/entity/allergy.entity.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts

- issue
- Product search api를 추가했어요!

[feat] search api 추가

---

frontend/src/App.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/pages/Mypage/Review.tsx

- LUP-70
- CSS 수정
- MobileWrapper css 수정, reviewHistory page route 추가

[fix] MobileWrapper css 수정, reviewHistory page route 추가

---

backend/package.json
backend/src/app.controller.ts
backend/src/app.module.ts
backend/src/entity/productReview.entity.ts
backend/src/main.ts
backend/src/mypage/mypage.controller.ts
backend/src/pet/dto/createPet.dto.ts
backend/src/pet/pet.controller.ts
backend/src/pet/pet.module.ts
backend/src/pet/pet.service.ts
backend/src/product/dto/food.dto.ts
backend/src/product/dto/getProductResponse.dto.ts
backend/src/product/dto/product.dto.ts
backend/src/product/dto/snack.dto.ts
backend/src/product/dto/supplement.dto.ts
backend/src/product/product.controller.ts
backend/src/product/product.service.ts
backend/src/review/dto/createReviewRequest.dto.ts
backend/src/review/dto/createReviewResponse.dto.ts
backend/src/review/dto/review.dto.ts
backend/src/review/review.controller.ts
backend/src/review/review.module.ts
backend/src/review/review.service.ts

- pet-create-update api 추가
- review 생성 및 조회 api 추가
- swagger 설명 추가
- --watch 설정
- v1로 버전 관리 추가

[feat] review 조회, 생성 및 pet 정보 생성 api 추가

---

backend/src/entity/pet.entity.ts
backend/src/entity/product.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts

- issue
- import 에러가 떠 import를 추가 및 수정했습니다.

[fix] import 수정

---

backend/src/entity/pet.entity.ts
backend/src/entity/product.entity.ts
backend/src/entity/snack.entity.ts
backend/src/entity/supplement.entity.ts
backend/src/product/product.module.ts
backend/src/review/review.service.ts

- issue
- init 주석 처리 및 import typo 수정

[fix] init 주석 처리 및 import typo 수정

---

frontend/src/App.tsx
frontend/src/components/common/Footer/Footer.tsx
frontend/src/components/common/Typo/index.tsx
frontend/src/components/signup/PetInfo.tsx
frontend/src/pages/Signup/Result.tsx

- LUP-45
- 로그인/회원가입 구현
- sign up result 화면 구현

[feat] signup result 화면 구현

---

backend/src/cart/cart.controller.ts
backend/src/cart/cart.service.ts
backend/src/cart/dto/addProductCart.dto.ts
backend/src/cart/dto/updateProductCart.dto.ts

- 장바구니 상품 수정
- updateProductCart API 구현

[feat(be)] 장바구니 상품 수정

---

backend/src/cart/cart.controller.ts
backend/src/cart/cart.service.ts
backend/src/cart/dto/deleteProduct.dto.ts
backend/src/entity/cart.product.entity.ts

- 장바구니 선택한 상품 삭제
- Cart API에 deleteProduct 추가

[feat(be)] 장바구니 원하는 상품 삭제

---

backend/src/cart/cart.service.ts
backend/src/cart/dto/CartItem.dto.ts
backend/src/cart/dto/getCartsResponse.dto.ts
backend/src/entity/cart.product.entity.ts
backend/src/entity/product.entity.ts

- 장바구니 조회 품목 수정
- 장바구니 조회 시 productImg, price, title 추가

[refact] 장바구니 조회 품목 수정

---

backend/src/cart/cart.controller.ts

- 장바구니 update 요청 방식 수정
- Post -> Patch로 변경

[refact] 장바구니 update 요청 방식 수정

---

backend/src/mypage/mypage.controller.ts
backend/src/mypage/mypage.service.ts

- 마이페이지 반환값 수정
- 명세서에서 기존 펫 정보 -> 유저 정보 포함으로 수정하였습니다.

[refact]마이페이지 반환값 수정

---

backend/src/mypage/dto/getUserResponse.dto.ts

- 마이페이지 dto 파일 추가
- dto 파일 오류난 부분 해결

[fix] 마이페이지 dto 파일 추가

---

frontend/src/apis/getCartList.ts
frontend/src/apis/hooks/useCartQuery.ts
frontend/src/mocks/handler.ts
frontend/src/pages/Cart/index.tsx
frontend/src/stores/cartStore.ts

- LUP-96
- 장바구니 조회 api 연결 및 tanstack query 적용
- cartStore에 cartItem set, add hook 추가

[feat] 장바구니 조회 API 연결 및 tanstack query 적용

---

frontend/src/apis/common/user.ts
frontend/src/apis/getCartList.ts
frontend/src/apis/getProductList.ts
frontend/src/apis/getTopProductLis.ts
frontend/src/apis/getUserReviewDone.ts
frontend/src/apis/getUserReviewRemain.ts
frontend/src/apis/hooks/useCartQuery.ts
frontend/src/apis/hooks/useProductList.ts
frontend/src/pages/Mypage/index.tsx
frontend/src/pages/Store/index.tsx

- LUP-22
- 리액트 쿼리 코드 수정
- 상품 목록 리스트를 조회하는 getProductList에 리액트 쿼리 적용
- 카드 목록을 조회하는 getCartList 리액트 쿼리 코드 수정

feat: getProductList reactQuery 적용(LUP-22)

---

backend/src/order/order.controller.ts
backend/src/order/order.module.ts
backend/src/order/order.service.ts

- 리뷰할 상품 조회
- order_item, order, user 테이블 조인
- order_state가 "결제 완료" 값인 정보 조회
- user, product_review, product을 통해 리뷰가 해당 상품에 대한 리뷰를 적었는지 판단
- 리뷰를 적지 않았고 "결제 완료"인 값들을 최종 조회

[feat]리뷰할 상품 조회

---

backend/src/cart/cart.service.ts

- 장바구니 상품 수정 및 삭제 수정
- Dto 연결 수정했습니다.

[fix] 장바구니 상품 수정 및 삭제 수정

---

backend/src/order/order.controller.ts

- 토큰 값으로 리뷰 불러오기
- 기존 유저의 uuid에서 -> 토큰 값으로 조회로 변경하였습니다(스웨거 반영)

[refact] 토큰값으로 리뷰 불러오기

---

backend/src/order/order.service.ts

- 반환값 수정
- 리뷰 해야 할 상품의 정보를 review 배열에 넣었습니다

[refact] 반환값 수정

---

backend/src/order/order.controller.ts
backend/src/order/order.service.ts

- change return value
- change return value

[refact] change return value

---

frontend/package.json
frontend/src/apis/hooks/cart.tsx
frontend/src/apis/hooks/review.tsx
frontend/src/components/Address/index.tsx
frontend/src/components/common/Modal/Modal.tsx
frontend/src/components/store/StickyFooter/index.tsx
frontend/src/components/store/detail/ProductReview.tsx
frontend/src/pages/Cart/index.tsx
frontend/src/pages/Payment/index.tsx
frontend/src/pages/Store/Detail.tsx
frontend/yarn.lock

[feat] payment modal

---

backend/src/cart/cart.controller.ts
backend/src/mypage/mypage.controller.ts
backend/src/pet/pet.controller.ts
frontend/src/apis/hooks/cart.tsx
frontend/src/apis/hooks/review.tsx
frontend/src/components/common/Modal/Modal.tsx
frontend/src/components/store/StickyFooter/index.tsx
frontend/src/components/store/detail/ProductReview.tsx
frontend/src/pages/Cart/index.tsx
frontend/src/pages/Store/Detail.tsx

[refact(be)] 코드 명세서 수정

---

backend/src/cart/cart.service.ts
backend/src/configs/setupSwagger.ts
backend/src/entity/cart.product.entity.ts
backend/src/entity/order.entity.ts
backend/src/entity/orderItem.entity.ts
backend/src/entity/productReview.entity.ts
backend/src/order/dto/PartialOrderItem.dto.ts
backend/src/order/dto/confirmOrderResponse.dto.ts
backend/src/order/dto/tempOrderRequest.dto.ts
backend/src/order/order.controller.ts
backend/src/order/order.module.ts
backend/src/order/order.service.ts
backend/src/pet/dto/petInfo.dto.ts
backend/src/review/dto/review.dto.ts
backend/src/review/review.controller.ts
backend/src/review/review.service.ts

- 결제 api
- order 관련 api
- 결제 승인 api
- 결제 승인 시 장바구니에서 물품 삭제
- 물품 리뷰 가져오기 Response 에 pet 정보 추가

[feat] 결제 및 order 관련 api 추가

---

backend/src/cart/cart.controller.ts
backend/src/cart/dto/addProductCart.dto.ts
backend/src/cart/dto/deleteProduct.dto.ts
backend/src/cart/dto/updateProductCart.dto.ts
backend/src/mypage/dto/updatePetRequest.dto.ts
backend/src/mypage/mypage.controller.ts
backend/src/order/dto/tempOrderRequest.dto.ts
backend/src/order/order.controller.ts
backend/src/pet/dto/petInfo.dto.ts
backend/src/pet/pet.controller.ts
backend/src/review/review.controller.ts

- null 값 유효성 검사
- controller에 validationPipe 추가
- dto에 IsNotEmpty, IsString, IsNumber 등 추가

[refact] null 값 유효성 검사

---

backend/package.json
backend/src/main.ts

[fix] 모듈 추가

---

backend/src/cart/cart.module.ts
backend/src/cart/cart.service.ts
backend/src/order/dto/tempOrderRequest.dto.ts
backend/src/order/order.controller.ts
backend/src/order/order.module.ts
backend/src/order/order.service.ts
backend/src/product/product.service.ts
frontend/src/apis/order.tsx
frontend/src/assets/types/OrderType.ts
frontend/src/pages/Payment/Fail.tsx
frontend/src/pages/Payment/Success.tsx
frontend/src/pages/Payment/TossPayment.tsx

[feat] 결제 api 연동 및 수정

---

backend/src/cart/cart.module.ts
backend/src/cart/cart.service.ts
backend/src/order/dto/tempOrderRequest.dto.ts
backend/src/order/order.controller.ts
backend/src/order/order.module.ts
backend/src/order/order.service.ts
backend/src/product/product.service.ts
frontend/src/App.tsx
frontend/src/apis/order.tsx
frontend/src/assets/types/OrderType.ts
frontend/src/components/health/Allergy.tsx
frontend/src/components/mypage/profile/index.tsx
frontend/src/components/store/Select/index.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Mypage/Order.tsx
frontend/src/pages/Mypage/Review.tsx
frontend/src/pages/Mypage/index.tsx
frontend/src/pages/Payment/Fail.tsx
frontend/src/pages/Payment/Success.tsx
frontend/src/pages/Payment/TossPayment.tsx
frontend/src/pages/Payment/index.tsx

- LUP-113
- 기타 자잘한 수정사항들
- 마이페이지 관련 스타일 코드 수정
- 결제페이지 Input창 추가

[feat] 마이페이지 관련 코드 수정, 결제페이지 Input창 추가

---

backend/src/product/product.service.ts
backend/src/review/review.module.ts
backend/src/review/review.service.ts

- updateAverageScore 메소드 추가
- 리뷰 생성 시 리뷰 평균 점수를 계산하는 로직을 추가하였습니다.
- 스웨거에서 상품 상세 조회 부분에서 averageScore 값을 확인할 수 있습니다.

[feat] updateAverageScore 메소드 추가

---

backend/src/mypage/dto/updatePetRequest.dto.ts
frontend/src/apis/hooks/mypage.tsx
frontend/src/apis/hooks/user.tsx
frontend/src/pages/Mypage/Modify.tsx
frontend/src/pages/Mypage/index.tsx

- LUP-119
- 비동기함수 관련 코드 수정
- 백엔드 코드 수정(중성화 여부 컬럼값)
- 반려견 정보 수정 후 마이페이지로 이동
- 이동 시 수정사항이 바로 반영되도록 변경
- 마이페이지 진입 시에 user 전역 변수 변경되도록 수정

[fix] 비동기 함수 관련 코드 수정

---

frontend/src/components/common/Modal/Modal.tsx

- z-index 수정
- modal 컴포넌트와 stickyfooter z-index 수정

[chore] z-index 수정

---

backend/src/entity/health.entity.ts
backend/src/health/health.controller.ts
backend/src/health/health.module.ts
backend/src/health/health.service.ts
backend/src/order/order.controller.ts
backend/src/review/review.controller.ts
backend/src/review/review.service.ts

- issue
- health api 및 리뷰 작성해야 하는 물품 api 수정

[feat] health api 및 리뷰 작성해야 하는 물품 api 수정

---

frontend/src/apis/hooks/useCartQuery.ts
frontend/src/components/cart/CartItem/index.tsx
frontend/src/pages/Cart/index.tsx
frontend/src/stores/cartStore.ts

- LUP-96
- 장바구니 수정 API 연결
- 장바구니 삭제 API 연결
- 장바구니 수정 API는 디바운스로 호출
- 장바구니 삭제 버튼 클릭 시 확인 모달창 띄우기 추가

[feat] 장바구니 수정, 삭제 API 연결

---

backend/.gitignore
backend/src/auth/auth.controller.ts
backend/src/entity/recommandProduct.entity.ts
backend/src/health/dto/recommandProduct.dto.ts
backend/src/health/health.module.ts
backend/src/health/health.service.ts
backend/src/order/order.service.ts

- issue
- 주문 내역에 결제 취소 출력 및 건강 진단 api에 recommand product 추가

[fix] 주문 내역에 결제 취소 출력 및 건강 진단 api에 recommand product 추가 

---

backend/src/cart/cart.controller.ts
backend/src/cart/cart.service.ts
backend/src/cart/dto/deleteProduct.dto.ts
backend/src/configs/typeorm.config.ts
backend/src/entity/health.entity.ts
backend/src/entity/pet.entity.ts
backend/src/entity/recommandProduct.entity.ts
backend/src/health/dto/aiHealthReponse.dto.ts
backend/src/health/dto/recommandProduct.dto.ts
backend/src/health/health.module.ts
backend/src/health/health.service.ts
backend/src/order/order.service.ts

- issue
- 백엔드 버그 fix 및 다중 cart 삭제 api로 카드 물품 삭제 수정

[fix] 백엔드 버그 fix 및 다중 cart 삭제 api로 카드 물품 삭제 수정

---

frontend/src/apis/health.tsx
frontend/src/apis/hooks/health.tsx
frontend/src/components/health/Loading.tsx
frontend/src/components/health/Recommend.tsx
frontend/src/components/home/HealthHistory.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Store/index.tsx

- LUP-131
- 영양 분석 내역 컴포넌트 추가 수정
- hook에서 데이터 받아오는 변수 수정
- 건강 분석 시 로티 loop true 설정

fix: hook 코드 수정(LUP-131)

---

backend/src/cart/dto/deleteProduct.dto.ts
backend/src/health/health.service.ts
frontend/src/components/skeleton/Skeleton.stories.tsx
frontend/src/components/skeleton/Skeleton.tsx
frontend/src/components/skeleton/index.tsx
frontend/src/pages/Store/index.tsx

- issue
- Skeleton ui 추가 및 백엔드 버그 수정

[feat] Skeleton ui 추가 및 백엔드 버그 수정

---

backend/src/order/order.service.ts
backend/src/review/review.module.ts
backend/src/review/review.service.ts

[fix] bug-fix

---

.github/workflows/frontend-prod-cd.yml

- issue
- 배포를 위한 깃허브 액션 추가했습니다.

[chore] 프론트엔드 github action 추가

---

.github/workflows/frontend-prod-cd.yml

chore: fe github action 추가
- issue
- description

[release] 프론트엔드 github action 추가 (#125)

---

backend/src/health/health.service.ts

- issue
- ai 추천 물품 중복 금지 명령 추가했습니다.

[fix] ai 추천 물품 중복 금지 추가

---

frontend/src/pages/Home.tsx

- LUP-133
- 홈 화면 Top10 상품 averageScore 반영

[fix] 홈 화면 averageScore 반영

---

frontend/src/components/home/HealthHistory.tsx

[hotfix] 글자 오류 수정

---

.github/workflows/frontend-prod-cd.yml
backend/src/health/health.service.ts
frontend/src/components/cart/CartItem/index.tsx
frontend/src/components/cart/Checkbox/index.tsx
frontend/src/components/common/Header/index.tsx
frontend/src/components/common/Layout/index.tsx
frontend/src/components/health/Recommend.tsx
frontend/src/components/home/HealthHistory.tsx
frontend/src/components/mypage/orderHistory/index.tsx
frontend/src/components/mypage/profile/index.tsx
frontend/src/components/search/SearchResult.tsx
frontend/src/components/store/Hr/index.tsx
frontend/src/components/store/detail/ProductReview.tsx
frontend/src/components/store/detail/ProductReviewItem.tsx
frontend/src/pages/Cart/index.tsx
frontend/src/pages/Health/Result.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/Mypage/Order.tsx
frontend/src/pages/Mypage/index.tsx
frontend/src/pages/Payment/index.tsx
frontend/src/pages/Store/Detail.tsx
frontend/src/pages/Store/index.tsx

[release] 1.1.2

---

backend/src/entity/recommendProduct.entity.ts
backend/src/health/dto/aiHealthReponse.dto.ts
backend/src/health/dto/recommendProduct.dto.ts
backend/src/health/health.module.ts
backend/src/health/health.service.ts
backend/src/mypage/mypage.controller.ts
frontend/src/apis/health.tsx
frontend/src/apis/hooks/cart.tsx
frontend/src/apis/hooks/order.tsx
frontend/src/apis/hooks/review.tsx
frontend/src/assets/images/svgs/CloseIcon/WhiteCloseIcon.tsx
frontend/src/assets/images/svgs/CloseIcon/index.tsx
frontend/src/components/health/CurFood.tsx
frontend/src/components/health/Loading.tsx
frontend/src/components/health/Recommend.tsx
frontend/src/components/home/HealthHistory.tsx
frontend/src/components/mypage/orderHistory/index.tsx
frontend/src/components/payment/Address.tsx
frontend/src/components/search/SearchResult.tsx
frontend/src/pages/Health/Result.tsx
frontend/src/pages/Payment/Success.tsx
frontend/src/pages/Payment/index.tsx
frontend/src/pages/Search/index.tsx
frontend/src/pages/Store/Detail.tsx

[hotfix] 오타 수정
